language: node_js
branches:
  only:
    - master
cache:
  diretories:
    - node_modules
notifications:
  email: false
node_js:
  - '7.5'
before_script:
  - npm prune && npm cache clean
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
env:
  global:
    - DOCS_DIR="dist/docs"
    - REPO="https://github.com/coosto/ShortcutJS"