language: node_js
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune && npm cache clean
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release